@startuml
entity "User" as user {
  * uid : INT <<PK>>
  --
  name : VARCHAR(20)
  email : VARCHAR(50)
  password : VARCHAR(50)
  user_type : VARCHAR(20)
  last_login : DATETIME
}

entity "Food" as food {
  * fid : INT <<PK>>
  --
  fname : VARCHAR(50)
  expiration : DATE
  price : DECIMAL(8,0)
  inventory : INT
  discount : DOUBLE
  ftid : INT
  is_donate : INT
  store_id : INT
}

entity "FoodType" as food_type {
  * id : INT <<PK>>
  --
  name : VARCHAR(255)
}

entity "Orders" as orders {
  * oid : INT <<PK>>
  --
  uid : INT <<FK>>
  fid : INT <<FK>>
  money : DECIMAL(8,2)
  num : INT
  purchase_date : TIMESTAMP
}

entity "Store" as store {
  * store_id : INT <<PK>>
  --
  store_name : VARCHAR(50)
  city : VARCHAR(50)
  uid : INT <<FK>>
}

entity "Subscribe" as subscribe {
  * sid : INT <<PK>>
  --
  uid : INT <<FK>>
  fid : INT <<FK>>
  create_time : DATE
  alert_type : VARCHAR(255)
  email : VARCHAR(255)
}

entity "RatingAndFeedback" as rating_and_feedback {
  * RatingID : INT <<PK>>
  --
  UserID : INT <<FK>>
  FoodID : INT <<FK>>
  Rating : INT
  Review : TEXT
  CreatedAt : TIMESTAMP
}

entity "Claims" as claims {
  * claim_id : INT <<PK>>
  --
  food_id : INT <<FK>>
  quantity : INT
  organization_id : INT <<FK>>
  claim_date : TIMESTAMP
}

user ||--o{ orders : "uid"
food ||--o{ orders : "fid"
user ||--o{ subscribe : "uid"
food ||--o{ subscribe : "fid"
user ||--o{ rating_and_feedback : "UserID"
food ||--o{ rating_and_feedback : "FoodID"
user ||--o{ claims : "organization_id"
food ||--o{ claims : "food_id"
food_type ||--o{ food : "ftid"
store ||--o{ food : "store_id"
user ||--o{ store : "uid"

@enduml
