@startuml
actor users
boundary loginPage 
boundary dashboardPage
boundary signupPage
control LoginServlet
participant AuthService
participant UserService
database mysql order 8
group login
users -> loginPage:login request
loginPage -> LoginServlet: login
LoginServlet -> AuthService:login
AuthService -> UserDao:getUserByEmail
UserDao -> mysql
mysql --> UserDao
UserDao --> AuthService: return user
AuthService --> LoginServlet: return check result

alt login successful

    LoginServlet --> dashboardPage
    dashboardpage --> users

else login failure
    LoginServlet --> loginPage
    loginPage --> users
end
end

group logout
users -> dashboardPage: logout
dashboardPage -> LoginServlet:logout
LoginServlet -> AuthService:logout
LoginServlet --> loginPage
loginPage --> users
end

group sign up

users -> signupPage:sign up
signupPage -> LoginServlet: signUp
LoginServlet -> UserService:signUp
UserService -> UserDao: insert user
UserDao -> mysql: insert user
UserDao --> UserService: return insert result
UserService --> LoginServlet: return sign up result
    alt register succefully
        LoginServlet --> loginPage:show success message
        loginPage --> users
    else register failure
        LoginServlet --> signupPage:show failure message
        signupPage --> users
    end 
end

@enduml
